# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_delegation.proto

# google protobuf file automatically generated for FlexRAN
import sys
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x:x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_delegation.proto',
  package='protocol',
  serialized_pb=_b('\n\x18\x63ontrol_delegation.proto\x12\x08protocol*=\n\x1c\x66lex_control_delegation_type\x12\x1d\n\x19\x46LCDT_MAC_DL_UE_SCHEDULER\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FLEX_CONTROL_DELEGATION_TYPE = _descriptor.EnumDescriptor(
  name='flex_control_delegation_type',
  full_name='protocol.flex_control_delegation_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLCDT_MAC_DL_UE_SCHEDULER', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=38,
  serialized_end=99,
)
_sym_db.RegisterEnumDescriptor(_FLEX_CONTROL_DELEGATION_TYPE)

flex_control_delegation_type = enum_type_wrapper.EnumTypeWrapper(_FLEX_CONTROL_DELEGATION_TYPE)
FLCDT_MAC_DL_UE_SCHEDULER = 1


DESCRIPTOR.enum_types_by_name['flex_control_delegation_type'] = _FLEX_CONTROL_DELEGATION_TYPE


# @@protoc_insertion_point(module_scope)
