# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller_commands.proto

# google protobuf file automatically generated for FlexRAN
import sys
import marc_flexran.flexran_msg.mac_primitives_pb2 as mac_primitives_pb2
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller_commands.proto',
  package='protocol',
  serialized_pb=_b('\n\x19\x63ontroller_commands.proto\x12\x08protocol\x1a\x14mac_primitives.proto\"\xae\x01\n\x0c\x66lex_dl_data\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12%\n\x06\x64l_dci\x18\x02 \x01(\x0b\x32\x15.protocol.flex_dl_dci\x12\x11\n\tce_bitmap\x18\x03 \x03(\r\x12\'\n\x07rlc_pdu\x18\x04 \x03(\x0b\x32\x16.protocol.flex_rlc_pdu\x12\x17\n\x0fserv_cell_index\x18\x05 \x01(\r\x12\x14\n\x0c\x61\x63t_deact_ce\x18\x06 \x01(\r\"i\n\x0b\x66lex_dl_rar\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\r\n\x05grant\x18\x02 \x01(\r\x12&\n\x07rar_dci\x18\x03 \x01(\x0b\x32\x15.protocol.flex_dl_dci\x12\x15\n\rcarrier_index\x18\x04 \x01(\r\"q\n\x11\x66lex_dl_broadcast\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\x12(\n\tbroad_dci\x18\x03 \x01(\x0b\x32\x15.protocol.flex_dl_dci\x12\x15\n\rcarrier_index\x18\x04 \x01(\r\"R\n\x19\x66lex_pdcch_ofdm_sym_count\x12\x15\n\rcarrier_index\x18\x01 \x01(\r\x12\x1e\n\x16num_pdcch_ofdm_symbols\x18\x02 \x01(\r*3\n\x13\x66lex_broadcast_type\x12\r\n\tFLBT_BCCH\x10\x00\x12\r\n\tFLBT_PCCH\x10\x01')
  ,
  dependencies=[mac_primitives_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FLEX_BROADCAST_TYPE = _descriptor.EnumDescriptor(
  name='flex_broadcast_type',
  full_name='protocol.flex_broadcast_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLBT_BCCH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLBT_PCCH', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=544,
  serialized_end=595,
)
_sym_db.RegisterEnumDescriptor(_FLEX_BROADCAST_TYPE)

flex_broadcast_type = enum_type_wrapper.EnumTypeWrapper(_FLEX_BROADCAST_TYPE)
FLBT_BCCH = 0
FLBT_PCCH = 1



_FLEX_DL_DATA = _descriptor.Descriptor(
  name='flex_dl_data',
  full_name='protocol.flex_dl_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_dl_data.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dl_dci', full_name='protocol.flex_dl_data.dl_dci', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ce_bitmap', full_name='protocol.flex_dl_data.ce_bitmap', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rlc_pdu', full_name='protocol.flex_dl_data.rlc_pdu', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serv_cell_index', full_name='protocol.flex_dl_data.serv_cell_index', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='act_deact_ce', full_name='protocol.flex_dl_data.act_deact_ce', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=236,
)


_FLEX_DL_RAR = _descriptor.Descriptor(
  name='flex_dl_rar',
  full_name='protocol.flex_dl_rar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_dl_rar.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grant', full_name='protocol.flex_dl_rar.grant', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rar_dci', full_name='protocol.flex_dl_rar.rar_dci', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.flex_dl_rar.carrier_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=343,
)


_FLEX_DL_BROADCAST = _descriptor.Descriptor(
  name='flex_dl_broadcast',
  full_name='protocol.flex_dl_broadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protocol.flex_dl_broadcast.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='protocol.flex_dl_broadcast.index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='broad_dci', full_name='protocol.flex_dl_broadcast.broad_dci', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.flex_dl_broadcast.carrier_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=458,
)


_FLEX_PDCCH_OFDM_SYM_COUNT = _descriptor.Descriptor(
  name='flex_pdcch_ofdm_sym_count',
  full_name='protocol.flex_pdcch_ofdm_sym_count',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.flex_pdcch_ofdm_sym_count.carrier_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_pdcch_ofdm_symbols', full_name='protocol.flex_pdcch_ofdm_sym_count.num_pdcch_ofdm_symbols', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=542,
)

_FLEX_DL_DATA.fields_by_name['dl_dci'].message_type = mac_primitives_pb2._FLEX_DL_DCI
_FLEX_DL_DATA.fields_by_name['rlc_pdu'].message_type = mac_primitives_pb2._FLEX_RLC_PDU
_FLEX_DL_RAR.fields_by_name['rar_dci'].message_type = mac_primitives_pb2._FLEX_DL_DCI
_FLEX_DL_BROADCAST.fields_by_name['broad_dci'].message_type = mac_primitives_pb2._FLEX_DL_DCI
DESCRIPTOR.message_types_by_name['flex_dl_data'] = _FLEX_DL_DATA
DESCRIPTOR.message_types_by_name['flex_dl_rar'] = _FLEX_DL_RAR
DESCRIPTOR.message_types_by_name['flex_dl_broadcast'] = _FLEX_DL_BROADCAST
DESCRIPTOR.message_types_by_name['flex_pdcch_ofdm_sym_count'] = _FLEX_PDCCH_OFDM_SYM_COUNT
DESCRIPTOR.enum_types_by_name['flex_broadcast_type'] = _FLEX_BROADCAST_TYPE

flex_dl_data = _reflection.GeneratedProtocolMessageType('flex_dl_data', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_DL_DATA,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_dl_data)
  ))
_sym_db.RegisterMessage(flex_dl_data)

flex_dl_rar = _reflection.GeneratedProtocolMessageType('flex_dl_rar', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_DL_RAR,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_dl_rar)
  ))
_sym_db.RegisterMessage(flex_dl_rar)

flex_dl_broadcast = _reflection.GeneratedProtocolMessageType('flex_dl_broadcast', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_DL_BROADCAST,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_dl_broadcast)
  ))
_sym_db.RegisterMessage(flex_dl_broadcast)

flex_pdcch_ofdm_sym_count = _reflection.GeneratedProtocolMessageType('flex_pdcch_ofdm_sym_count', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_PDCCH_OFDM_SYM_COUNT,
  __module__ = 'controller_commands_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_pdcch_ofdm_sym_count)
  ))
_sym_db.RegisterMessage(flex_pdcch_ofdm_sym_count)


# @@protoc_insertion_point(module_scope)
