# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mac_primitives.proto

# google protobuf file automatically generated for FlexRAN
import sys
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='mac_primitives.proto',
  package='protocol',
  serialized_pb=_b('\n\x14mac_primitives.proto\x12\x08protocol\"\x82\x04\n\x0b\x66lex_dl_dci\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x11\n\tres_alloc\x18\x02 \x01(\r\x12\x11\n\trb_bitmap\x18\x03 \x01(\r\x12\x10\n\x08rb_shift\x18\x04 \x01(\r\x12\x10\n\x08tbs_size\x18\x05 \x03(\r\x12\x0b\n\x03mcs\x18\x06 \x03(\r\x12\x0b\n\x03ndi\x18\x07 \x03(\r\x12\n\n\x02rv\x18\x08 \x03(\r\x12\x11\n\tcce_index\x18\t \x01(\r\x12\x12\n\naggr_level\x18\n \x01(\r\x12\x16\n\x0eprecoding_info\x18\x0b \x01(\r\x12\x0e\n\x06\x66ormat\x18\x0c \x01(\r\x12\x0b\n\x03tpc\x18\r \x01(\r\x12\x14\n\x0charq_process\x18\x0e \x01(\r\x12\x0b\n\x03\x64\x61i\x18\x0f \x01(\r\x12\x12\n\nvrb_format\x18\x10 \x01(\r\x12\x0f\n\x07tb_swap\x18\x11 \x01(\r\x12\x13\n\x0bsps_release\x18\x12 \x01(\r\x12\x13\n\x0bpdcch_order\x18\x13 \x01(\r\x12\x16\n\x0epreamble_index\x18\x14 \x01(\r\x12\x18\n\x10prach_mask_index\x18\x15 \x01(\r\x12\r\n\x05n_gap\x18\x16 \x01(\r\x12\x0f\n\x07tbs_idx\x18\x17 \x01(\r\x12\x17\n\x0f\x64l_power_offset\x18\x18 \x01(\r\x12\x1a\n\x12pdcch_power_offset\x18\x19 \x01(\r\x12\x13\n\x0b\x63if_present\x18\x1a \x01(\r\x12\x0b\n\x03\x63if\x18\x1b \x01(\r\"=\n\x0c\x66lex_rlc_pdu\x12-\n\nrlc_pdu_tb\x18\x01 \x03(\x0b\x32\x19.protocol.flex_rlc_pdu_tb\";\n\x0f\x66lex_rlc_pdu_tb\x12\x1a\n\x12logical_channel_id\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r*\xa4\x01\n\x0f\x66lex_dci_format\x12\x0c\n\x08\x46LDCIF_1\x10\x00\x12\r\n\tFLDCIF_1A\x10\x01\x12\r\n\tFLDCIF_1B\x10\x02\x12\r\n\tFLDCIF_1C\x10\x03\x12\r\n\tFLDCIF_1D\x10\x04\x12\x0c\n\x08\x46LDCIF_2\x10\x05\x12\r\n\tFLDCIF_2A\x10\x06\x12\r\n\tFLDCIF_2B\x10\x07\x12\x0c\n\x08\x46LDCIF_3\x10\x08\x12\r\n\tFLDCIF_3A\x10\t*?\n\x0f\x66lex_vrb_format\x12\x14\n\x10\x46LVRBF_LOCALIZED\x10\x00\x12\x16\n\x12\x46LVRBF_DISTRIBUTED\x10\x01*)\n\rflex_ngap_val\x12\x0b\n\x07\x46LNGV_1\x10\x00\x12\x0b\n\x07\x46LNGV_2\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FLEX_DCI_FORMAT = _descriptor.EnumDescriptor(
  name='flex_dci_format',
  full_name='protocol.flex_dci_format',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_1A', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_1B', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_1C', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_1D', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_2', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_2A', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_2B', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_3', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLDCIF_3A', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=676,
  serialized_end=840,
)
_sym_db.RegisterEnumDescriptor(_FLEX_DCI_FORMAT)

flex_dci_format = enum_type_wrapper.EnumTypeWrapper(_FLEX_DCI_FORMAT)
_FLEX_VRB_FORMAT = _descriptor.EnumDescriptor(
  name='flex_vrb_format',
  full_name='protocol.flex_vrb_format',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLVRBF_LOCALIZED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLVRBF_DISTRIBUTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=842,
  serialized_end=905,
)
_sym_db.RegisterEnumDescriptor(_FLEX_VRB_FORMAT)

flex_vrb_format = enum_type_wrapper.EnumTypeWrapper(_FLEX_VRB_FORMAT)
_FLEX_NGAP_VAL = _descriptor.EnumDescriptor(
  name='flex_ngap_val',
  full_name='protocol.flex_ngap_val',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLNGV_1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLNGV_2', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=907,
  serialized_end=948,
)
_sym_db.RegisterEnumDescriptor(_FLEX_NGAP_VAL)

flex_ngap_val = enum_type_wrapper.EnumTypeWrapper(_FLEX_NGAP_VAL)
FLDCIF_1 = 0
FLDCIF_1A = 1
FLDCIF_1B = 2
FLDCIF_1C = 3
FLDCIF_1D = 4
FLDCIF_2 = 5
FLDCIF_2A = 6
FLDCIF_2B = 7
FLDCIF_3 = 8
FLDCIF_3A = 9
FLVRBF_LOCALIZED = 0
FLVRBF_DISTRIBUTED = 1
FLNGV_1 = 0
FLNGV_2 = 1



_FLEX_DL_DCI = _descriptor.Descriptor(
  name='flex_dl_dci',
  full_name='protocol.flex_dl_dci',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_dl_dci.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res_alloc', full_name='protocol.flex_dl_dci.res_alloc', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rb_bitmap', full_name='protocol.flex_dl_dci.rb_bitmap', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rb_shift', full_name='protocol.flex_dl_dci.rb_shift', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tbs_size', full_name='protocol.flex_dl_dci.tbs_size', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mcs', full_name='protocol.flex_dl_dci.mcs', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ndi', full_name='protocol.flex_dl_dci.ndi', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rv', full_name='protocol.flex_dl_dci.rv', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cce_index', full_name='protocol.flex_dl_dci.cce_index', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggr_level', full_name='protocol.flex_dl_dci.aggr_level', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='precoding_info', full_name='protocol.flex_dl_dci.precoding_info', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='protocol.flex_dl_dci.format', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tpc', full_name='protocol.flex_dl_dci.tpc', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='harq_process', full_name='protocol.flex_dl_dci.harq_process', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dai', full_name='protocol.flex_dl_dci.dai', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vrb_format', full_name='protocol.flex_dl_dci.vrb_format', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tb_swap', full_name='protocol.flex_dl_dci.tb_swap', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sps_release', full_name='protocol.flex_dl_dci.sps_release', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdcch_order', full_name='protocol.flex_dl_dci.pdcch_order', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preamble_index', full_name='protocol.flex_dl_dci.preamble_index', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prach_mask_index', full_name='protocol.flex_dl_dci.prach_mask_index', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_gap', full_name='protocol.flex_dl_dci.n_gap', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tbs_idx', full_name='protocol.flex_dl_dci.tbs_idx', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dl_power_offset', full_name='protocol.flex_dl_dci.dl_power_offset', index=23,
      number=24, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdcch_power_offset', full_name='protocol.flex_dl_dci.pdcch_power_offset', index=24,
      number=25, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cif_present', full_name='protocol.flex_dl_dci.cif_present', index=25,
      number=26, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cif', full_name='protocol.flex_dl_dci.cif', index=26,
      number=27, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=549,
)


_FLEX_RLC_PDU = _descriptor.Descriptor(
  name='flex_rlc_pdu',
  full_name='protocol.flex_rlc_pdu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rlc_pdu_tb', full_name='protocol.flex_rlc_pdu.rlc_pdu_tb', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=612,
)


_FLEX_RLC_PDU_TB = _descriptor.Descriptor(
  name='flex_rlc_pdu_tb',
  full_name='protocol.flex_rlc_pdu_tb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logical_channel_id', full_name='protocol.flex_rlc_pdu_tb.logical_channel_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='protocol.flex_rlc_pdu_tb.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=673,
)

_FLEX_RLC_PDU.fields_by_name['rlc_pdu_tb'].message_type = _FLEX_RLC_PDU_TB
DESCRIPTOR.message_types_by_name['flex_dl_dci'] = _FLEX_DL_DCI
DESCRIPTOR.message_types_by_name['flex_rlc_pdu'] = _FLEX_RLC_PDU
DESCRIPTOR.message_types_by_name['flex_rlc_pdu_tb'] = _FLEX_RLC_PDU_TB
DESCRIPTOR.enum_types_by_name['flex_dci_format'] = _FLEX_DCI_FORMAT
DESCRIPTOR.enum_types_by_name['flex_vrb_format'] = _FLEX_VRB_FORMAT
DESCRIPTOR.enum_types_by_name['flex_ngap_val'] = _FLEX_NGAP_VAL

flex_dl_dci = _reflection.GeneratedProtocolMessageType('flex_dl_dci', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_DL_DCI,
  __module__ = 'mac_primitives_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_dl_dci)
  ))
_sym_db.RegisterMessage(flex_dl_dci)

flex_rlc_pdu = _reflection.GeneratedProtocolMessageType('flex_rlc_pdu', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_RLC_PDU,
  __module__ = 'mac_primitives_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_rlc_pdu)
  ))
_sym_db.RegisterMessage(flex_rlc_pdu)

flex_rlc_pdu_tb = _reflection.GeneratedProtocolMessageType('flex_rlc_pdu_tb', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_RLC_PDU_TB,
  __module__ = 'mac_primitives_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_rlc_pdu_tb)
  ))
_sym_db.RegisterMessage(flex_rlc_pdu_tb)


# @@protoc_insertion_point(module_scope)
