# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats_messages.proto

# google protobuf file automatically generated for FlexRAN
import sys
import marc_flexran.flexran_msg.stats_common_pb2 as stats_common_pb2

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_b=sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))

DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats_messages.proto',
  package='protocol',
  serialized_pb=_b('\n\x14stats_messages.proto\x12\x08protocol\x1a\x12stats_common.proto\"\x99\x01\n\x1b\x66lex_complete_stats_request\x12:\n\x10report_frequency\x18\x01 \x01(\x0e\x32 .protocol.flex_stats_report_freq\x12\n\n\x02sf\x18\x02 \x01(\r\x12\x19\n\x11\x63\x65ll_report_flags\x18\x03 \x01(\r\x12\x17\n\x0fue_report_flags\x18\x04 \x01(\r\"6\n\x17\x66lex_cell_stats_request\x12\x0c\n\x04\x63\x65ll\x18\x01 \x03(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\"4\n\x15\x66lex_ue_stats_request\x12\x0c\n\x04rnti\x18\x01 \x03(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\"\x84\x01\n\x16\x66lex_cell_stats_report\x12\x15\n\rcarrier_index\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\x12\x44\n\x12noise_inter_report\x18\x03 \x01(\x0b\x32(.protocol.flex_noise_interference_report\"\xae\x02\n\x14\x66lex_ue_stats_report\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\r\x12\x0b\n\x03\x62sr\x18\x03 \x03(\r\x12\x0b\n\x03phr\x18\x04 \x01(\r\x12*\n\nrlc_report\x18\x05 \x03(\x0b\x32\x16.protocol.flex_rlc_bsr\x12\x17\n\x0fpending_mac_ces\x18\x06 \x01(\r\x12\x33\n\rdl_cqi_report\x18\x07 \x01(\x0b\x32\x1c.protocol.flex_dl_cqi_report\x12\x30\n\x03pbr\x18\x08 \x01(\x0b\x32#.protocol.flex_paging_buffer_report\x12\x33\n\rul_cqi_report\x18\t \x01(\x0b\x32\x1c.protocol.flex_ul_cqi_report*R\n\x0f\x66lex_stats_type\x12\x17\n\x13\x46LST_COMPLETE_STATS\x10\x00\x12\x13\n\x0f\x46LST_CELL_STATS\x10\x01\x12\x11\n\rFLST_UE_STATS\x10\x02*c\n\x16\x66lex_stats_report_freq\x12\x0e\n\nFLSRF_ONCE\x10\x00\x12\x14\n\x10\x46LSRF_PERIODICAL\x10\x01\x12\x14\n\x10\x46LSRF_CONTINUOUS\x10\x02\x12\r\n\tFLSRF_OFF\x10\x03*4\n\x14\x66lex_cell_stats_type\x12\x1c\n\x18\x46LCST_NOISE_INTERFERENCE\x10\x01*\x8c\x01\n\x12\x66lex_ue_stats_type\x12\r\n\tFLUST_BSR\x10\x01\x12\r\n\tFLUST_PRH\x10\x02\x12\x10\n\x0c\x46LUST_RLC_BS\x10\x04\x12\x13\n\x0f\x46LUST_MAC_CE_BS\x10\x08\x12\x10\n\x0c\x46LUST_DL_CQI\x10\x10\x12\r\n\tFLUST_PBS\x10 \x12\x10\n\x0c\x46LUST_UL_CQI\x10@')
  ,
  dependencies=[stats_common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FLEX_STATS_TYPE = _descriptor.EnumDescriptor(
  name='flex_stats_type',
  full_name='protocol.flex_stats_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLST_COMPLETE_STATS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLST_CELL_STATS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLST_UE_STATS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=760,
  serialized_end=842,
)
_sym_db.RegisterEnumDescriptor(_FLEX_STATS_TYPE)

flex_stats_type = enum_type_wrapper.EnumTypeWrapper(_FLEX_STATS_TYPE)
_FLEX_STATS_REPORT_FREQ = _descriptor.EnumDescriptor(
  name='flex_stats_report_freq',
  full_name='protocol.flex_stats_report_freq',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLSRF_ONCE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLSRF_PERIODICAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLSRF_CONTINUOUS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLSRF_OFF', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=844,
  serialized_end=943,
)
_sym_db.RegisterEnumDescriptor(_FLEX_STATS_REPORT_FREQ)

flex_stats_report_freq = enum_type_wrapper.EnumTypeWrapper(_FLEX_STATS_REPORT_FREQ)
_FLEX_CELL_STATS_TYPE = _descriptor.EnumDescriptor(
  name='flex_cell_stats_type',
  full_name='protocol.flex_cell_stats_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLCST_NOISE_INTERFERENCE', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=945,
  serialized_end=997,
)
_sym_db.RegisterEnumDescriptor(_FLEX_CELL_STATS_TYPE)

flex_cell_stats_type = enum_type_wrapper.EnumTypeWrapper(_FLEX_CELL_STATS_TYPE)
_FLEX_UE_STATS_TYPE = _descriptor.EnumDescriptor(
  name='flex_ue_stats_type',
  full_name='protocol.flex_ue_stats_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLUST_BSR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUST_PRH', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUST_RLC_BS', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUST_MAC_CE_BS', index=3, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUST_DL_CQI', index=4, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUST_PBS', index=5, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLUST_UL_CQI', index=6, number=64,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1000,
  serialized_end=1140,
)
_sym_db.RegisterEnumDescriptor(_FLEX_UE_STATS_TYPE)

flex_ue_stats_type = enum_type_wrapper.EnumTypeWrapper(_FLEX_UE_STATS_TYPE)
FLST_COMPLETE_STATS = 0
FLST_CELL_STATS = 1
FLST_UE_STATS = 2
FLSRF_ONCE = 0
FLSRF_PERIODICAL = 1
FLSRF_CONTINUOUS = 2
FLSRF_OFF = 3
FLCST_NOISE_INTERFERENCE = 1
FLUST_BSR = 1
FLUST_PRH = 2
FLUST_RLC_BS = 4
FLUST_MAC_CE_BS = 8
FLUST_DL_CQI = 16
FLUST_PBS = 32
FLUST_UL_CQI = 64



_FLEX_COMPLETE_STATS_REQUEST = _descriptor.Descriptor(
  name='flex_complete_stats_request',
  full_name='protocol.flex_complete_stats_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='report_frequency', full_name='protocol.flex_complete_stats_request.report_frequency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sf', full_name='protocol.flex_complete_stats_request.sf', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_report_flags', full_name='protocol.flex_complete_stats_request.cell_report_flags', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ue_report_flags', full_name='protocol.flex_complete_stats_request.ue_report_flags', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=208,
)


_FLEX_CELL_STATS_REQUEST = _descriptor.Descriptor(
  name='flex_cell_stats_request',
  full_name='protocol.flex_cell_stats_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell', full_name='protocol.flex_cell_stats_request.cell', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='protocol.flex_cell_stats_request.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=264,
)


_FLEX_UE_STATS_REQUEST = _descriptor.Descriptor(
  name='flex_ue_stats_request',
  full_name='protocol.flex_ue_stats_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_ue_stats_request.rnti', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='protocol.flex_ue_stats_request.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=318,
)


_FLEX_CELL_STATS_REPORT = _descriptor.Descriptor(
  name='flex_cell_stats_report',
  full_name='protocol.flex_cell_stats_report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='carrier_index', full_name='protocol.flex_cell_stats_report.carrier_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='protocol.flex_cell_stats_report.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noise_inter_report', full_name='protocol.flex_cell_stats_report.noise_inter_report', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=453,
)


_FLEX_UE_STATS_REPORT = _descriptor.Descriptor(
  name='flex_ue_stats_report',
  full_name='protocol.flex_ue_stats_report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_ue_stats_report.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='protocol.flex_ue_stats_report.flags', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bsr', full_name='protocol.flex_ue_stats_report.bsr', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phr', full_name='protocol.flex_ue_stats_report.phr', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rlc_report', full_name='protocol.flex_ue_stats_report.rlc_report', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pending_mac_ces', full_name='protocol.flex_ue_stats_report.pending_mac_ces', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dl_cqi_report', full_name='protocol.flex_ue_stats_report.dl_cqi_report', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pbr', full_name='protocol.flex_ue_stats_report.pbr', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ul_cqi_report', full_name='protocol.flex_ue_stats_report.ul_cqi_report', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=758,
)

_FLEX_COMPLETE_STATS_REQUEST.fields_by_name['report_frequency'].enum_type = _FLEX_STATS_REPORT_FREQ
_FLEX_CELL_STATS_REPORT.fields_by_name['noise_inter_report'].message_type = stats_common_pb2._FLEX_NOISE_INTERFERENCE_REPORT
_FLEX_UE_STATS_REPORT.fields_by_name['rlc_report'].message_type = stats_common_pb2._FLEX_RLC_BSR
_FLEX_UE_STATS_REPORT.fields_by_name['dl_cqi_report'].message_type = stats_common_pb2._FLEX_DL_CQI_REPORT
_FLEX_UE_STATS_REPORT.fields_by_name['pbr'].message_type = stats_common_pb2._FLEX_PAGING_BUFFER_REPORT
_FLEX_UE_STATS_REPORT.fields_by_name['ul_cqi_report'].message_type = stats_common_pb2._FLEX_UL_CQI_REPORT
DESCRIPTOR.message_types_by_name['flex_complete_stats_request'] = _FLEX_COMPLETE_STATS_REQUEST
DESCRIPTOR.message_types_by_name['flex_cell_stats_request'] = _FLEX_CELL_STATS_REQUEST
DESCRIPTOR.message_types_by_name['flex_ue_stats_request'] = _FLEX_UE_STATS_REQUEST
DESCRIPTOR.message_types_by_name['flex_cell_stats_report'] = _FLEX_CELL_STATS_REPORT
DESCRIPTOR.message_types_by_name['flex_ue_stats_report'] = _FLEX_UE_STATS_REPORT
DESCRIPTOR.enum_types_by_name['flex_stats_type'] = _FLEX_STATS_TYPE
DESCRIPTOR.enum_types_by_name['flex_stats_report_freq'] = _FLEX_STATS_REPORT_FREQ
DESCRIPTOR.enum_types_by_name['flex_cell_stats_type'] = _FLEX_CELL_STATS_TYPE
DESCRIPTOR.enum_types_by_name['flex_ue_stats_type'] = _FLEX_UE_STATS_TYPE

flex_complete_stats_request = _reflection.GeneratedProtocolMessageType('flex_complete_stats_request', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_COMPLETE_STATS_REQUEST,
  __module__ = 'stats_messages_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_complete_stats_request)
  ))
_sym_db.RegisterMessage(flex_complete_stats_request)

flex_cell_stats_request = _reflection.GeneratedProtocolMessageType('flex_cell_stats_request', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_CELL_STATS_REQUEST,
  __module__ = 'stats_messages_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_cell_stats_request)
  ))
_sym_db.RegisterMessage(flex_cell_stats_request)

flex_ue_stats_request = _reflection.GeneratedProtocolMessageType('flex_ue_stats_request', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_UE_STATS_REQUEST,
  __module__ = 'stats_messages_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_ue_stats_request)
  ))
_sym_db.RegisterMessage(flex_ue_stats_request)

flex_cell_stats_report = _reflection.GeneratedProtocolMessageType('flex_cell_stats_report', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_CELL_STATS_REPORT,
  __module__ = 'stats_messages_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_cell_stats_report)
  ))
_sym_db.RegisterMessage(flex_cell_stats_report)

flex_ue_stats_report = _reflection.GeneratedProtocolMessageType('flex_ue_stats_report', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_UE_STATS_REPORT,
  __module__ = 'stats_messages_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_ue_stats_report)
  ))
_sym_db.RegisterMessage(flex_ue_stats_report)


# @@protoc_insertion_point(module_scope)
