# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_common.proto

# google protobuf file automatically generated for FlexRAN
import sys

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))


DESCRIPTOR = _descriptor.FileDescriptor(
  name='time_common.proto',
  package='protocol',
  serialized_pb=_b('\n\x11time_common.proto\x12\x08protocol\"c\n\x0c\x66lex_dl_info\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x17\n\x0fharq_process_id\x18\x02 \x01(\r\x12\x13\n\x0bharq_status\x18\x03 \x03(\r\x12\x17\n\x0fserv_cell_index\x18\x04 \x01(\r\"r\n\x0c\x66lex_ul_info\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x14\n\x0cul_reception\x18\x02 \x03(\r\x12\x18\n\x10reception_status\x18\x03 \x01(\r\x12\x0b\n\x03tpc\x18\x04 \x01(\r\x12\x17\n\x0fserv_cell_index\x18\x05 \x01(\r*=\n\x10\x66lex_harq_status\x12\x0c\n\x08\x46LHS_ACK\x10\x00\x12\r\n\tFLHS_NACK\x10\x01\x12\x0c\n\x08\x46LHS_DTX\x10\x02*I\n\x15\x66lex_reception_status\x12\x0b\n\x07\x46LRS_OK\x10\x00\x12\x0f\n\x0b\x46LRS_NOT_OK\x10\x01\x12\x12\n\x0e\x46LRS_NOT_VALID\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FLEX_HARQ_STATUS = _descriptor.EnumDescriptor(
  name='flex_harq_status',
  full_name='protocol.flex_harq_status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLHS_ACK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLHS_NACK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLHS_DTX', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=248,
  serialized_end=309,
)
_sym_db.RegisterEnumDescriptor(_FLEX_HARQ_STATUS)

flex_harq_status = enum_type_wrapper.EnumTypeWrapper(_FLEX_HARQ_STATUS)
_FLEX_RECEPTION_STATUS = _descriptor.EnumDescriptor(
  name='flex_reception_status',
  full_name='protocol.flex_reception_status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLRS_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLRS_NOT_OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLRS_NOT_VALID', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=311,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_FLEX_RECEPTION_STATUS)

flex_reception_status = enum_type_wrapper.EnumTypeWrapper(_FLEX_RECEPTION_STATUS)
FLHS_ACK = 0
FLHS_NACK = 1
FLHS_DTX = 2
FLRS_OK = 0
FLRS_NOT_OK = 1
FLRS_NOT_VALID = 2



_FLEX_DL_INFO = _descriptor.Descriptor(
  name='flex_dl_info',
  full_name='protocol.flex_dl_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_dl_info.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='harq_process_id', full_name='protocol.flex_dl_info.harq_process_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='harq_status', full_name='protocol.flex_dl_info.harq_status', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serv_cell_index', full_name='protocol.flex_dl_info.serv_cell_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=130,
)


_FLEX_UL_INFO = _descriptor.Descriptor(
  name='flex_ul_info',
  full_name='protocol.flex_ul_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnti', full_name='protocol.flex_ul_info.rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ul_reception', full_name='protocol.flex_ul_info.ul_reception', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reception_status', full_name='protocol.flex_ul_info.reception_status', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tpc', full_name='protocol.flex_ul_info.tpc', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serv_cell_index', full_name='protocol.flex_ul_info.serv_cell_index', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['flex_dl_info'] = _FLEX_DL_INFO
DESCRIPTOR.message_types_by_name['flex_ul_info'] = _FLEX_UL_INFO
DESCRIPTOR.enum_types_by_name['flex_harq_status'] = _FLEX_HARQ_STATUS
DESCRIPTOR.enum_types_by_name['flex_reception_status'] = _FLEX_RECEPTION_STATUS

flex_dl_info = _reflection.GeneratedProtocolMessageType('flex_dl_info', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_DL_INFO,
  __module__ = 'time_common_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_dl_info)
  ))
_sym_db.RegisterMessage(flex_dl_info)

flex_ul_info = _reflection.GeneratedProtocolMessageType('flex_ul_info', (_message.Message,), dict(
  DESCRIPTOR = _FLEX_UL_INFO,
  __module__ = 'time_common_pb2'
  # @@protoc_insertion_point(class_scope:protocol.flex_ul_info)
  ))
_sym_db.RegisterMessage(flex_ul_info)


# @@protoc_insertion_point(module_scope)
